sudo: 'required'

services:
  - docker

before_install:
  - 'sudo bash ./build.sh'
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'

script:
  - 'sudo bash ./deploy.sh'