FROM winetree94/ubuntu-android-builder:base
MAINTAINER winetree94@outlook.com

RUN $ANDROID_HOME/tools/bin/sdkmanager \
    "build-tools;29.0.0" \
    "build-tools;28.0.3" \
    "build-tools;28.0.2" \
    "build-tools;27.0.3" \
    "build-tools;27.0.2" \
    "build-tools;27.0.1" \
    "build-tools;26.0.2" \
    "platforms;android-23" \
    "platforms;android-24" \
    "platforms;android-25" \
    "platforms;android-26" \
    "platforms;android-27" \
    "platforms;android-28" \
    "platform-tools"